<div id="atomik-wrapper">
  <div id="main">
    <div id="header">
      <h1>¡Puzzle!</h1>
      <h2>Compartir</h2>
      <form action="http://www.facebook.com/share.php">
        <input type="hidden" name="u" id="puzzle-url" value="">
        <input type="hidden" name="t" value="¡Puzzle!">
        <input type="submit" class="btn-facebook" value="" />
      </form>
    </div>
    <div id="content">
      <div id="puzzle">
      </div>
      <div id="tip-container">
        <div id="tip-status">
        </div>
        <div id="tip">
        </div>
      </div>
    </div>
    <div id="footer">
    </div>
  </div>
</div>
